Print failed tests during runtests.
Slightly more useful than failing and leaving you to dissect which
test(s) actually caused the failure.

diff --git a/tests/runtests b/tests/runtests
--- a/tests/runtests
+++ b/tests/runtests
@@ -15,7 +15,8 @@ find . -nowarn \
        ! -path './.*' -and \
        -type f -and \
        -executable -and \
-       ! -exec {} \; \
+       ! -exec {} \; -and \
+       -exec echo "FAILED: {}" 1>&2 \; -and \
        -exec touch failure-indicator  \;
 
 if [ -e failure-indicator ]; then
